jobs:
  workflow:
    name: Workflow
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Pull Dependencies
        run: sudo apt-get update && sudo apt-get install -y libhwloc15 unrar
      - name: Execute Tests
        run: ./ci/action

name: Ci

on:
  schedule:
    - cron: "25 1/3 * * *"
